//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Check.
        /// </summary>
        internal static string CheckAction {
            get {
                return ResourceManager.GetString("CheckAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your action:.
        /// </summary>
        internal static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the game dificulty:.
        /// </summary>
        internal static string ChooseDifficulty {
            get {
                return ResourceManager.GetString("ChooseDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command fail, try again!.
        /// </summary>
        internal static string CommandFailMessage {
            get {
                return ResourceManager.GetString("CommandFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Easy.
        /// </summary>
        internal static string EasyDifficultyOption {
            get {
                return ResourceManager.GetString("EasyDifficultyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Flag.
        /// </summary>
        internal static string FlagAction {
            get {
                return ResourceManager.GetString("FlagAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Hard.
        /// </summary>
        internal static string HardDifficultyOption {
            get {
                return ResourceManager.GetString("HardDifficultyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option invalid!.
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Medium.
        /// </summary>
        internal static string MediumDifficultyOption {
            get {
                return ResourceManager.GetString("MediumDifficultyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collumn:.
        /// </summary>
        internal static string ReadCollumn {
            get {
                return ResourceManager.GetString("ReadCollumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row:.
        /// </summary>
        internal static string ReadRow {
            get {
                return ResourceManager.GetString("ReadRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Try again!.
        /// </summary>
        internal static string TryAgainMessage {
            get {
                return ResourceManager.GetString("TryAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Unflag.
        /// </summary>
        internal static string UnflagAction {
            get {
                return ResourceManager.GetString("UnflagAction", resourceCulture);
            }
        }
    }
}
