//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minesweeper.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can&apos;t be set quantity bombs near in a checked cell..
        /// </summary>
        internal static string CellIsCheckedBombsNear {
            get {
                return ResourceManager.GetString("CellIsCheckedBombsNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can&apos;t be place a bomb in a checked cell..
        /// </summary>
        internal static string CellIsCheckedPlaceBomb {
            get {
                return ResourceManager.GetString("CellIsCheckedPlaceBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can&apos;t be checked a flagged cell..
        /// </summary>
        internal static string CellIsFlagged {
            get {
                return ResourceManager.GetString("CellIsFlagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cell is already revealed..
        /// </summary>
        internal static string CellIsReavealed {
            get {
                return ResourceManager.GetString("CellIsReavealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cell already has bomb.
        /// </summary>
        internal static string FieldAlreadyHasBomb {
            get {
                return ResourceManager.GetString("FieldAlreadyHasBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over!.
        /// </summary>
        internal static string GameOverMessage {
            get {
                return ResourceManager.GetString("GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bomb quantity.
        /// </summary>
        internal static string InvalidBombQuantity {
            get {
                return ResourceManager.GetString("InvalidBombQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid game level!.
        /// </summary>
        internal static string InvalidGameLevel {
            get {
                return ResourceManager.GetString("InvalidGameLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity bombs can&apos;t be bigger than fieldSize..
        /// </summary>
        internal static string QuantityBombsBiggerThanFieldSize {
            get {
                return ResourceManager.GetString("QuantityBombsBiggerThanFieldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can&apos;t be unflag a cell without flag..
        /// </summary>
        internal static string UnflagCellWithoutFlag {
            get {
                return ResourceManager.GetString("UnflagCellWithoutFlag", resourceCulture);
            }
        }
    }
}
